import { UeError } from "../../error";

export enum UeAiErrorCode {
    AI_REQUEST_FAILED = "ERROR:AI_REQUEST_FAILED",
    AI_AXIOS_NOT_INIT = "ERROR:AI_AXIOS_NOT_INIT",
    AI_REQUEST_TIMEOUT = "ERROR:AI_REQUEST_TIMEOUT",
    AI_REQUEST_ABORT = "ERROR:AI_REQUEST_ABORT",
    AI_REQUEST_UNKNOWN_ERROR = "ERROR:AI_REQUEST_UNKNOWN_ERROR",
    AI_REQUEST_STREAM_ERROR = "ERROR:AI_REQUEST_STREAM_ERROR",
    AI_REQUEST_STREAM_OUTPUT_ERROR = "ERROR:AI_REQUEST_STREAM_OUTPUT_ERROR",
}

export class UeAiError extends UeError<UeAiErrorCode> {}
