import { UeError } from "@stone/uemo-editor-utils/lib/error";

export enum UeElErrorCode {
    UPLOAD_FAILED = "ERROR:UPLOAD_FAILED",
    UPLOAD_ERROR = "ERROR:UPLOAD_ERROR",
    UPLOAD_FILE_SIZE_EXCEED = "ERROR:UPLOAD_FILE_SIZE_EXCEED",
    UPLOAD_NETWORK_ERROR = "ERROR:UPLOAD_NETWORK_ERROR",
    UPLOAD_GET_QINIU_TOKEN_FAILED = "ERROR:UPLOAD_GET_QINIU_TOKEN_FAILED",
    UPLOAD_NOT_CONFIG_QINIU = "ERROR:UPLOAD_NOT_CONFIG_QINIU",
    UPLOAD_NOT_ALLOW_IMAGE = "ERROR:UPLOAD_NOT_ALLOW_IMAGE",
    UPLOAD_NOT_SELECTED = "ERROR:UPLOAD_NOT_SELECTED",
    UPLOAD_NOT_CONFIG = "ERROR:UPLOAD_NOT_CONFIG",
    UPLOAD_NOT_ALLOW_VIDEO = "ERROR:UPLOAD_NOT_ALLOW_VIDEO",
}

export class UeElError extends UeError<UeElErrorCode> {}
