// ResourceRichTextType

export type ResourceRichTextItem = {
    theme: "lighter" | "darker" | "all";
    value: string;
    thumb: string;
};

export type ResourceRichText = ResourceRichTextItem[];

const richTextLib: ResourceRichText = [
    { theme: "all", thumb: require("./image/000.png"), value: `<p></p>` },
    {
        theme: "lighter",
        thumb: require("./image/001.png"),
        value: `<div class="btn-row-c58e4 text-14-c6e02" style="--btn-row-gap: 1em; font-size: 14px; text-align: center"><div class="btn-list-a1de5"><div class="btn-ece02" target="_blank" data-theme="custom" data-link-type="link" style="--padding: 1px 15px;--color: rgb(0, 0, 0);--border-radius: 125px;--border-width: 1px;--border-color: rgb(221, 221, 221);--background: rgb(255, 255, 255);--border-style: solid;"><div class="btn-text-d97c4">Web editor Try it</div></div></div></div><p style="text-align: center"></p><p style="text-align: center"><strong><span style="color: rgb(0, 0, 0); font-family: PlusJakartaSans-ExtraBold; font-size: 60px; line-height: 1.25" class="text-60-d6566">Title001</span></strong></p><p style="text-align: center"><strong><span style="color: rgb(0, 0, 0); font-size: 60px; line-height: 1.25" class="text-60-d6566">板块标题内容</span></strong></p><p style="text-align: center"></p><p style="text-align: center"><span style="color: rgb(102, 102, 102); font-size: 16px; line-height: 2" class="text-16-d4745">拥有快速搭建、自由编辑、多屏适配、无需代码等特点，是您打造充满魅力的网站最理想的选择。</span></p><div class="editor-divide-block-a1327" style="--divide-block-size: 50px; --divide-block-md-size: 40px"></div><div class="btn-row-c58e4 text-14-c6e02" style="--btn-row-gap: 1em; font-size: 14px; text-align: center"><div class="btn-list-a1de5"><a class="btn-ece02" href="http://resources.jsmo.xin/templates/upload/15415/201908/1567074726390.png" target="_blank" data-theme="custom" data-link-type="frame" style="--padding: 10px 30px;--color: rgb(255, 255, 255);--box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.1);--hover-box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.15);--border-radius: 100px;--background: rgb(51, 51, 51);"><div class="btn-text-d97c4">View more</div></a><a class="btn-ece02" href="http://resources.jsmo.xin/templates/upload/15415/201908/1567074726390.png" target="_blank" data-theme="custom" data-link-type="frame" style="--padding: 10px 30px;--color: rgb(0, 0, 0);--box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.1);--hover-box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.15);--border-radius: 100px;--background: rgb(255, 255, 255);--hover-background: rgb(255, 255, 255);"><div class="btn-text-d97c4">Watch tutorials</div></a></div></div><p></p>`,
    },
    {
        theme: "darker",
        thumb: require("./image/003.png"),
        value: `<div class="btn-row-c58e4 text-14-c6e02" style="--btn-row-gap: 1em; font-size: 14px; text-align: center"><div class="btn-list-a1de5"><div class="btn-ece02" target="_blank" data-theme="custom" data-link-type="link" style="--padding: 1px 15px;--color: rgb(255, 255, 255);--border-radius: 125px;--border-width: 1px;--border-color: rgba(255, 255, 255, 0.3);--border-style: solid;"><div class="btn-text-d97c4">Web editor Try it</div></div></div></div><p style="text-align: center"></p><p style="text-align: center"><strong><span style="color: rgb(255, 255, 255); font-family: PlusJakartaSans-ExtraBold; font-size: 60px; line-height: 1.25" class="text-60-d6566">Title001</span></strong></p><p style="text-align: center"><strong><span style="color: rgb(255, 255, 255); font-size: 60px; line-height: 1.25" class="text-60-d6566">板块标题内容</span></strong></p><p style="text-align: center"></p><p style="text-align: center"><span style="color: rgba(255, 255, 255, 0.6); font-size: 16px; line-height: 2" class="text-16-d4745">拥有快速搭建、自由编辑、多屏适配、无需代码等特点，是您打造充满魅力的网站最理想的选择。</span></p><div class="editor-divide-block-a1327" style="--divide-block-size: 50px; --divide-block-md-size: 40px"></div><div class="btn-row-c58e4 text-14-c6e02" style="--btn-row-gap: 1em; font-size: 14px; text-align: center"><div class="btn-list-a1de5"><a class="btn-ece02" href="http://resources.jsmo.xin/templates/upload/15415/201908/1567074726390.png" target="_blank" data-theme="custom" data-link-type="frame" style="--padding: 10px 30px;--color: rgb(255, 255, 255);--box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.1);--hover-box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.15);--border-radius: 100px;--background: rgb(51, 51, 51);"><div class="btn-text-d97c4">View more</div></a><a class="btn-ece02" href="http://resources.jsmo.xin/templates/upload/15415/201908/1567074726390.png" target="_blank" data-theme="custom" data-link-type="frame" style="--padding: 10px 30px;--color: rgb(0, 0, 0);--box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.1);--hover-box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.15);--border-radius: 100px;--background: rgb(255, 255, 255);--hover-background: rgb(255, 255, 255);"><div class="btn-text-d97c4">Watch tutorials</div></a></div></div><p></p>`,
    },
    {
        theme: "lighter",
        thumb: require("./image/002.png"),
        value: `<div class="btn-row-c58e4 text-14-c6e02" style="--btn-row-gap: 1em; font-size: 14px"><div class="btn-list-a1de5"><div class="btn-ece02" target="_blank" data-theme="custom" data-link-type="link" style="--padding: 1px 15px;--color: rgb(102, 102, 102);--border-radius: 125px;--border-width: 2px;--border-color: rgb(199, 199, 199);--border-style: dashed;"><div class="btn-text-d97c4">标签属性</div></div></div></div><p></p><p><span style="color: rgb(0, 0, 0); font-family: PlusJakartaSans-ExtraBold; font-size: 60px; line-height: 1.25" class="text-60-d6566">Title01</span></p><p><strong><span style="color: rgb(0, 0, 0); font-size: 48px; line-height: 1.25" class="text-48-d26d5">板块标题内容</span></strong></p><p></p><p><span style="color: rgb(102, 102, 102); font-size: 16px; line-height: 2" class="text-16-d4745">拥有快速搭建、自由编辑、多屏适配、无需代码等特点，是您打造充满魅力的网站最理想的选择。</span></p>`,
    },
    {
        theme: "darker",
        thumb: require("./image/004.png"),
        value: `<div class="btn-row-c58e4 text-14-c6e02" style="--btn-row-gap: 1em; font-size: 14px"><div class="btn-list-a1de5"><div class="btn-ece02" target="_blank" data-theme="custom" data-link-type="link" style="--padding: 1px 15px;--color: rgba(255, 255, 255, 0.9);--border-radius: 125px;--border-width: 2px;--border-color: rgba(255, 255, 255, 0.4);--border-style: dashed;"><div class="btn-text-d97c4">标签属性</div></div></div></div><p></p><p><strong><span style="color: rgb(255, 255, 255); font-family: PlusJakartaSans-ExtraBold; font-size: 60px; line-height: 1.25" class="text-60-d6566">Title001</span></strong></p><p><strong><span style="color: rgb(255, 255, 255); font-size: 48px; line-height: 1.25" class="text-48-d26d5">板块标题内容</span></strong></p><p></p><p><span style="color: rgba(255, 255, 255, 0.6); font-size: 16px; line-height: 2" class="text-16-d4745">拥有快速搭建、自由编辑、多屏适配、无需代码等特点，是您打造充满魅力的网站最理想的选择。</span></p>`,
    },
    {
        theme: "lighter",
        thumb: require("./image/005.png"),
        value: `<div class="grid-layer-cb854" data-grid="1,1-1-1:1/1/2/2,1/2/2/3,1/3/2/4" data-md-grid="1,1-1-1:1/1/2/2,1/2/2/3,1/3/2/4"><div class="grid-layer--inner-ef909" style="--grid-template-columns: 1fr 1fr 1fr;--grid-template-rows: 1fr;--md-grid-template-columns: 1fr 1fr 1fr;--md-grid-template-rows: 1fr;gap: 10px;--md-grid-layer-gap: 10px;padding: 10px 0px;width: 100%;"><div class="grid-item-af6e7" style="grid-area: 1 / 1 / 2 / 2;--md-grid-layer-item-area: 1/1/2/2;"><div class="layer-page_bg-e0884"></div><div class="grid-item--inner-ae340"><p style="text-align: center"><span style="color: rgb(0, 0, 0); font-family: PlusJakartaSans-ExtraBold; font-size: 36px" class="text-36-bfb99">176</span></p><p style="text-align: center">所获奖项</p></div></div><div class="grid-item-af6e7" style="grid-area: 1 / 2 / 2 / 3;--md-grid-layer-item-area: 1/2/2/3;"><div class="layer-page_bg-e0884"></div><div class="grid-item--inner-ae340"><p style="text-align: center"><span style="color: rgb(0, 0, 0); font-family: PlusJakartaSans-ExtraBold; font-size: 36px" class="text-36-bfb99">35</span></p><p style="text-align: center">服务项目</p></div></div><div class="grid-item-af6e7" style="grid-area: 1 / 3 / 2 / 4;--md-grid-layer-item-area: 1/3/2/4;"><div class="layer-page_bg-e0884"></div><div class="grid-item--inner-ae340"><p style="text-align: center"><span style="color: rgb(0, 0, 0); font-family: PlusJakartaSans-ExtraBold; font-size: 36px" class="text-36-bfb99">326</span></p><p style="text-align: center">行业经验</p></div></div></div></div>`,
    },
    {
        theme: "darker",
        thumb: require("./image/008.png"),
        value: `<div class="grid-layer-cb854" data-grid="1,1-1-1:1/1/2/2,1/2/2/3,1/3/2/4" data-md-grid="1,1-1-1:1/1/2/2,1/2/2/3,1/3/2/4"><div class="grid-layer--inner-ef909" style="--grid-template-columns: 1fr 1fr 1fr;--grid-template-rows: 1fr;--md-grid-template-columns: 1fr 1fr 1fr;--md-grid-template-rows: 1fr;gap: 10px;--md-grid-layer-gap: 10px;padding: 10px 0px;width: 100%;"><div class="grid-item-af6e7" style="grid-area: 1 / 1 / 2 / 2;--md-grid-layer-item-area: 1/1/2/2;"><div class="layer-page_bg-e0884"></div><div class="grid-item--inner-ae340"><p style="text-align: center"><span style="color: rgb(255, 255, 255); font-family: PlusJakartaSans-ExtraBold; font-size: 36px" class="text-36-bfb99">176</span></p><p style="text-align: center"><span style="color: rgba(255, 255, 255, 0.6)">所获奖项</span></p></div></div><div class="grid-item-af6e7" style="grid-area: 1 / 2 / 2 / 3;--md-grid-layer-item-area: 1/2/2/3;"><div class="layer-page_bg-e0884"></div><div class="grid-item--inner-ae340"><p style="text-align: center"><span style="color: rgb(255, 255, 255); font-family: PlusJakartaSans-ExtraBold; font-size: 36px" class="text-36-bfb99">35</span></p><p style="text-align: center"><span style="color: rgba(255, 255, 255, 0.6)">服务项目</span></p></div></div><div class="grid-item-af6e7" style="grid-area: 1 / 3 / 2 / 4;--md-grid-layer-item-area: 1/3/2/4;"><div class="layer-page_bg-e0884"></div><div class="grid-item--inner-ae340"><p style="text-align: center"><span style="color: rgb(255, 255, 255); font-family: PlusJakartaSans-ExtraBold; font-size: 36px" class="text-36-bfb99">326</span></p><p style="text-align: center"><span style="color: rgba(255, 255, 255, 0.6)">行业经验</span></p></div></div></div></div>`,
    },
    {
        theme: "lighter",
        thumb: require("./image/006.png"),
        value: `<div class="svg-icon-wrapper-bb7c1" style="text-align:center"><div class="svg-icon-box-f2008" style="background: rgb(62, 62, 62);width: 80px;border-radius: 100px;color: rgb(255, 255, 255);padding: 20px;"><iconpark-icon class="svg-icon-viewer-ed4be" data-source="https://static.jsmo.xin/uebuilder/public-resource/svg-icon/icon-park/official/official.js" width="100%" height="100%" name="book-one"></iconpark-icon></div></div><div class="editor-divide-block-a1327" style="--divide-block-size: 50px; --divide-block-md-size: 40px"></div><p style="text-align: center"><strong><span style="color: rgb(0, 0, 0); font-size: 28px; line-height: 1.25" class="text-28-f2a19">板块标题内容</span></strong></p><div class="editor-divide-block-a1327" style="--divide-block-size: 20px; --divide-block-md-size: 20px"></div><p style="text-align: center"><span style="color: rgb(102, 102, 102); font-size: 16px; line-height: 2" class="text-16-d4745">拥有快速搭建、自由编辑、多屏适配、无需代码等特点，是您打造充满魅力的网站最理想的选择。</span></p><div class="editor-divide-block-a1327" style="--divide-block-size: 50px; --divide-block-md-size: 40px"></div><div class="btn-row-c58e4 text-14-c6e02" style="--btn-row-gap: 1em; font-size: 14px; text-align: center"><div class="btn-list-a1de5"><a class="btn-ece02" href="http://resources.jsmo.xin/templates/upload/15415/201908/1567074726390.png" target="_blank" data-theme="custom" data-link-type="frame" style="--padding: 8px 30px 8px 30px;--color: rgb(51, 51, 51);--border-radius: 100px;--border-width: 1px;--border-color: rgb(204, 204, 204);--border-style: solid;"><div class="btn-text-d97c4">了解更多</div><iconpark-icon name="arrow-right" data-source="https://static.jsmo.xin/uebuilder/public-resource/svg-icon/icon-park/arrows/arrows.js" class="btn-after-icon-bbc97 btn-icon-a4b75"></iconpark-icon></a></div></div>`,
    },
    {
        theme: "darker",
        thumb: require("./image/009.png"),
        value: `<div class="svg-icon-wrapper-bb7c1" style="text-align:center"><div class="svg-icon-box-f2008" style="background: rgba(255, 255, 255, 0.2);width: 80px;border-radius: 100px;color: rgb(255, 255, 255);padding: 20px;"><iconpark-icon class="svg-icon-viewer-ed4be" data-source="https://static.jsmo.xin/uebuilder/public-resource/svg-icon/icon-park/official/official.js" width="100%" height="100%" name="book-one"></iconpark-icon></div></div><div class="editor-divide-block-a1327" style="--divide-block-size: 50px; --divide-block-md-size: 40px"></div><p style="text-align: center"><strong><span style="color: rgb(255, 255, 255); font-size: 28px; line-height: 1.25" class="text-28-f2a19">板块标题内容</span></strong></p><div class="editor-divide-block-a1327" style="--divide-block-size: 20px; --divide-block-md-size: 20px"></div><p style="text-align: center"><span style="color: rgba(255, 255, 255, 0.6); font-size: 16px; line-height: 2" class="text-16-d4745">拥有快速搭建、自由编辑、多屏适配、无需代码等特点，是您打造充满魅力的网站最理想的选择。</span></p><div class="editor-divide-block-a1327" style="--divide-block-size: 50px; --divide-block-md-size: 40px"></div><div class="btn-row-c58e4 text-14-c6e02" style="--btn-row-gap: 1em; font-size: 14px; text-align: center"><div class="btn-list-a1de5"><a class="btn-ece02" href="http://resources.jsmo.xin/templates/upload/15415/201908/1567074726390.png" target="_blank" data-theme="custom" data-link-type="frame" style="--padding: 8px 30px 8px 30px;--color: rgb(255, 255, 255);--border-radius: 100px;--border-width: 1px;--border-color: rgba(255, 255, 255, 0.4);--border-style: solid;"><div class="btn-text-d97c4">了解更多</div><iconpark-icon name="arrow-right" data-source="https://static.jsmo.xin/uebuilder/public-resource/svg-icon/icon-park/arrows/arrows.js" class="btn-after-icon-bbc97 btn-icon-a4b75"></iconpark-icon></a></div></div>`,
    },
    {
        theme: "lighter",
        thumb: require("./image/007.png"),
        value: `<p style="text-align: center"><span style="color: rgb(0, 0, 0); font-family: PlusJakartaSans-ExtraBold; font-size: 60px" class="text-60-d6566">76%</span></p><div class="editor-divide-block-a1327" style="--divide-block-size: 40px; --divide-block-md-size: 30px"></div><p style="text-align: center"><strong><span style="color: rgb(0, 0, 0); font-size: 24px" class="text-24-ce6ae">板块标题内容</span></strong></p><div class="editor-divide-block-a1327" style="--divide-block-size: 20px; --divide-block-md-size: 10px"></div><p style="text-align: center"><span style="color: rgb(102, 102, 102); font-size: 16px; line-height: 2" class="text-16-d4745">拥有快速搭建、自由编辑、多屏适配、无需代码等特点，是您打造充满魅力的网站最理想的选择。</span></p>`,
    },
    {
        theme: "darker",
        thumb: require("./image/010.png"),
        value: `<p style="text-align: center"><span style="color: rgb(255, 255, 255); font-family: PlusJakartaSans-ExtraBold; font-size: 60px" class="text-60-d6566">76%</span></p><div class="editor-divide-block-a1327" style="--divide-block-size: 40px; --divide-block-md-size: 30px"></div><p style="text-align: center"><strong><span style="color: rgb(255, 255, 255); font-size: 24px" class="text-24-ce6ae">板块标题内容</span></strong></p><div class="editor-divide-block-a1327" style="--divide-block-size: 20px; --divide-block-md-size: 10px"></div><p style="text-align: center"><span style="color: rgba(255, 255, 255, 0.6); font-size: 16px; line-height: 2" class="text-16-d4745">拥有快速搭建、自由编辑、多屏适配、无需代码等特点，是您打造充满魅力的网站最理想的选择。</span></p><p style="text-align: center"></p>`,
    },
    {
        theme: "lighter",
        thumb: require("./image/011.png"),
        value: `<div class="grid-layer-cb854" data-grid="1,auto-1:1/1/2/2,1/2/2/3" data-md-grid="auto-auto,1:1/1/2/2,2/1/3/2"><div class="grid-layer--inner-ef909" style="--grid-template-columns: auto 1fr;--grid-template-rows: 1fr;--md-grid-template-columns: 1fr;--md-grid-template-rows: auto auto;gap: 10px 30px;--md-grid-layer-gap: 30px 10px;width: 100%;"><div class="grid-item-af6e7" style="grid-area: 1 / 1 / 2 / 2;overflow: hidden;"><div class="layer-page_bg-e0884"></div><div class="grid-item--inner-ae340"><div style="" class="img_wrapper-eb43b"><div class="image_item-ff7d7" data-image-ratio="1-1" style="width: 130px;border-radius: 10px;--ratio: 100%;"><div class="image_box-c5e00" style="background-image: url(https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?ixid=M3wxNzk2NDF8MHwxfHNlYXJjaHw0MXx8d2FsbHBhcGVyfHpoLUhhbnN8MXx8fHwxNjk4Mjk1NDkyfDA&amp;ixlib=rb-4.0.3&amp;w=1080);"><img src="https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?ixid=M3wxNzk2NDF8MHwxfHNlYXJjaHw0MXx8d2FsbHBhcGVyfHpoLUhhbnN8MXx8fHwxNjk4Mjk1NDkyfDA&amp;ixlib=rb-4.0.3&amp;w=1080" width="1080" height="608"></div></div></div></div></div><div class="grid-item-af6e7" style="grid-area: 1 / 2 / 2 / 3;overflow: hidden;"><div class="layer-page_bg-e0884"></div><div class="grid-item--inner-ae340"><p><span style="font-family: Arial">Branding</span></p><div class="editor-divide-block-a1327" style="--divide-block-size: 10px; --divide-block-md-size: 10px"></div><p><strong><span style="color: rgb(0, 0, 0); font-size: 20px; line-height: 1.25" class="text-20-e283b">板块标题内容</span></strong></p><div class="editor-divide-block-a1327" style="--divide-block-size: 20px; --divide-block-md-size: 20px"></div><p><span style="color: rgb(102, 102, 102); font-size: 14px; line-height: 2" class="text-14-c6e02">拥有快速搭建、自由编辑、多屏适配、无需代码等特点，是您打造充满魅力的网站最理想的选择。</span></p></div></div></div></div>`,
    },
    {
        theme: "darker",
        thumb: require("./image/013.png"),
        value: `<div class="grid-layer-cb854" data-grid="1,auto-1:1/1/2/2,1/2/2/3" data-md-grid="auto-auto,1:1/1/2/2,2/1/3/2"><div class="grid-layer--inner-ef909" style="--grid-template-columns: auto 1fr;--grid-template-rows: 1fr;--md-grid-template-columns: 1fr;--md-grid-template-rows: auto auto;gap: 10px 30px;--md-grid-layer-gap: 30px 10px;width: 100%;"><div class="grid-item-af6e7" style="grid-area: 1 / 1 / 2 / 2;overflow: hidden;"><div class="layer-page_bg-e0884"></div><div class="grid-item--inner-ae340"><div style="" class="img_wrapper-eb43b"><div class="image_item-ff7d7" data-image-ratio="1-1" style="width: 140px;border-radius: 10px;--ratio: 100%;"><div class="image_box-c5e00" style="background-image: url(https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?ixid=M3wxNzk2NDF8MHwxfHNlYXJjaHw0MXx8d2FsbHBhcGVyfHpoLUhhbnN8MXx8fHwxNjk4Mjk1NDkyfDA&amp;ixlib=rb-4.0.3&amp;w=1080);"><img src="https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?ixid=M3wxNzk2NDF8MHwxfHNlYXJjaHw0MXx8d2FsbHBhcGVyfHpoLUhhbnN8MXx8fHwxNjk4Mjk1NDkyfDA&amp;ixlib=rb-4.0.3&amp;w=1080" width="1080" height="608"></div></div></div></div></div><div class="grid-item-af6e7" style="grid-area: 1 / 2 / 2 / 3;overflow: hidden;"><div class="layer-page_bg-e0884"></div><div class="grid-item--inner-ae340"><p><span style="color: rgba(255, 255, 255, 0.6); font-family: Arial">Branding</span></p><div class="editor-divide-block-a1327" style="--divide-block-size: 10px; --divide-block-md-size: 10px"></div><p><strong><span style="color: rgb(255, 255, 255); font-size: 20px; line-height: 1.25" class="text-20-e283b">板块标题内容</span></strong></p><div class="editor-divide-block-a1327" style="--divide-block-size: 20px; --divide-block-md-size: 20px"></div><p><span style="color: rgba(255, 255, 255, 0.6); font-size: 14px; line-height: 2" class="text-14-c6e02">拥有快速搭建、自由编辑、多屏适配、无需代码等特点，是您打造充满魅力的网站最理想的选择。</span></p></div></div></div></div>`,
    },
    {
        theme: "lighter",
        thumb: require("./image/012.png"),
        value: `<div class="grid-layer-cb854" data-grid="1,auto-1:1/1/2/2,1/2/2/3" data-md-grid="auto-auto,1:1/1/2/2,2/1/3/2"><div class="grid-layer--inner-ef909" style="--grid-template-columns: auto 1fr;--grid-template-rows: 1fr;--md-grid-template-columns: 1fr;--md-grid-template-rows: auto auto;gap: 10px 30px;--md-grid-layer-gap: 10px;width: 100%;"><div class="grid-item-af6e7" style="grid-area: 1 / 1 / 2 / 2;overflow: hidden;"><div class="layer-page_bg-e0884"></div><div class="grid-item--inner-ae340"><div class="svg-icon-wrapper-bb7c1"><div class="svg-icon-box-f2008" style="width: 50px;color: rgb(0, 0, 0);"><iconpark-icon class="svg-icon-viewer-ed4be" data-source="https://static.jsmo.xin/uebuilder/public-resource/svg-icon/icon-park/charts/charts.js" width="100%" height="100%" name="analysis"></iconpark-icon></div></div></div></div><div class="grid-item-af6e7" style="grid-area: 1 / 2 / 2 / 3;overflow: hidden;"><div class="layer-page_bg-e0884"></div><div class="grid-item--inner-ae340"><div class="editor-divide-block-a1327" style="--divide-block-size: 10px; --divide-block-md-size: 20px"></div><p><strong><span style="color: rgb(0, 0, 0); font-size: 20px; line-height: 1.25" class="text-20-e283b">板块标题内容</span></strong></p><div class="editor-divide-block-a1327" style="--divide-block-size: 20px; --divide-block-md-size: 10px"></div><p><span style="color: rgb(102, 102, 102); font-size: 14px; line-height: 2" class="text-14-c6e02">拥有快速搭建、自由编辑、多屏适配、无需代码等特点，是您打造充满魅力的网站最理想的选择。</span></p></div></div></div></div>`,
    },
    {
        theme: "darker",
        thumb: require("./image/014.png"),
        value: `<div class="grid-layer-cb854" data-grid="1,auto-1:1/1/2/2,1/2/2/3" data-md-grid="auto-auto,1:1/1/2/2,2/1/3/2"><div class="grid-layer--inner-ef909" style="--grid-template-columns: auto 1fr;--grid-template-rows: 1fr;--md-grid-template-columns: 1fr;--md-grid-template-rows: auto auto;gap: 10px 30px;--md-grid-layer-gap: 10px;width: 100%;"><div class="grid-item-af6e7" style="grid-area: 1 / 1 / 2 / 2;overflow: hidden;"><div class="layer-page_bg-e0884"></div><div class="grid-item--inner-ae340"><div class="svg-icon-wrapper-bb7c1"><div class="svg-icon-box-f2008" style="width: 46px;color: rgb(255, 255, 255);"><iconpark-icon class="svg-icon-viewer-ed4be" data-source="https://static.jsmo.xin/uebuilder/public-resource/svg-icon/icon-park/charts/charts.js" width="100%" height="100%" name="analysis"></iconpark-icon></div></div></div></div><div class="grid-item-af6e7" style="grid-area: 1 / 2 / 2 / 3;overflow: hidden;"><div class="layer-page_bg-e0884"></div><div class="grid-item--inner-ae340"><div class="editor-divide-block-a1327" style="--divide-block-size: 10px; --divide-block-md-size: 20px"></div><p><strong><span style="color: rgb(255, 255, 255); font-size: 20px; line-height: 1.25" class="text-20-e283b">板块标题内容</span></strong></p><div class="editor-divide-block-a1327" style="--divide-block-size: 20px; --divide-block-md-size: 10px"></div><p><span style="color: rgba(255, 255, 255, 0.6); font-size: 14px; line-height: 2" class="text-14-c6e02">拥有快速搭建、自由编辑、多屏适配、无需代码等特点，是您打造充满魅力的网站最理想的选择。</span></p></div></div></div></div>`,
    },
];

export default richTextLib;
