import type { BUTTON_ITEM_PARAM } from "./type";

export type ResourceButtonItem = { id: string; attrs: BUTTON_ITEM_PARAM };
export type ResourceButton = Record<string, { name: string; options: ResourceButtonItem[] }>;

const btnLib: ResourceButton = {
    normal: {
        name: "常规",
        options: [
            {
                id: "normal-5",
                attrs: {
                    text: "BUTTON",
                    animation: "",
                    padding: "8px 30px",
                    theme: "custom",
                    beforeSvgIcon: undefined,
                    afterSvgIcon: {
                        name: "arrow-right",
                        source: "https://static.jsmo.xin/uebuilder/public-resource/svg-icon/icon-park/arrows/arrows.js",
                    },
                    transition: "1",
                    previewHover: "0",
                    radius: "100px",
                    hoverRadius: "",
                    color: "rgb(255, 96, 0)",
                    hoverColor: "rgb(255, 255, 255)",
                    background: "",
                    hoverBackground: "rgb(255, 96, 0)",
                    borderColor: "rgb(255, 96, 0)",
                    hoverBorderColor: "rgb(255, 96, 0)",
                    borderWidth: "2px",
                    hoverBorderWidth: "2px",
                    borderStyle: "solid",
                    hoverBorderStyle: "solid",
                    shadow: "",
                    hoverShadow: "",
                    link: "",
                    linkTarget: "_blank",
                    linkType: "link",
                    linkDetail: "",
                },
            },
            {
                id: "normal-6",
                attrs: {
                    text: "BUTTON",
                    animation: "",
                    padding: "8px 30px",
                    theme: "custom",
                    beforeSvgIcon: undefined,
                    afterSvgIcon: undefined,
                    transition: "1",
                    previewHover: "0",
                    radius: "8px",
                    hoverRadius: "",
                    color: "rgb(17, 99, 223)",
                    hoverColor: "rgb(255, 255, 255)",
                    background: "",
                    hoverBackground: "rgb(17, 99, 223)",
                    borderColor: "rgb(17, 99, 223)",
                    hoverBorderColor: "rgb(17, 99, 223)",
                    borderWidth: "2px",
                    hoverBorderWidth: "2px",
                    borderStyle: "solid",
                    hoverBorderStyle: "solid",
                    shadow: "",
                    hoverShadow: "",
                    link: "",
                    linkTarget: "_blank",
                    linkType: "link",
                    linkDetail: "",
                },
            },

            {
                id: "normal-2",
                attrs: {
                    text: "BUTTON",
                    animation: "",
                    padding: "8px 30px",
                    theme: "custom",
                    beforeSvgIcon: undefined,
                    afterSvgIcon: undefined,
                    transition: "1",
                    previewHover: "0",
                    radius: "100px",
                    hoverRadius: "",
                    color: "#ffffff",
                    hoverColor: "",
                    background: "linear-gradient(135deg, rgb(37, 170, 224) 0%, rgb(64, 227, 151) 100%)",
                    hoverBackground: "linear-gradient(90deg, rgb(37, 170, 224) 0%, rgb(72, 134, 241) 100%)",
                    borderColor: "",
                    hoverBorderColor: "",
                    borderWidth: "",
                    hoverBorderWidth: "",
                    borderStyle: "",
                    hoverBorderStyle: "",
                    shadow: "",
                    hoverShadow: "0 5px 10px 0 rgba(37, 122, 153, 0.3)",
                    link: "",
                    linkTarget: "_target",
                    linkType: "link",
                    linkDetail: "",
                },
            },
            {
                id: "normal-4",
                attrs: {
                    text: "BUTTON",
                    animation: "",
                    padding: "8px 30px",
                    theme: "custom",
                    beforeSvgIcon: undefined,
                    afterSvgIcon: undefined,
                    transition: "1",
                    previewHover: "0",
                    radius: "100px",
                    hoverRadius: "",
                    color: "#ffffff",
                    hoverColor: "",
                    background: "linear-gradient(135deg, rgb(100, 80, 220) 0%, rgb(164, 135, 255) 100%)",
                    hoverBackground: "linear-gradient(135deg, rgb(255, 108, 171) 0%, #7366ff 100%)",
                    borderColor: "",
                    hoverBorderColor: "",
                    borderWidth: "",
                    hoverBorderWidth: "",
                    borderStyle: "",
                    hoverBorderStyle: "",
                    shadow: "",
                    hoverShadow: "0 5px 10px 0 rgba(69, 0, 143, 0.3)",
                    link: "",
                    linkTarget: "_target",
                    linkType: "link",
                    linkDetail: "",
                },
            },

            {
                id: "normal-12",
                attrs: {
                    text: "BUTTON",
                    animation: "",
                    padding: "8px 20px",
                    theme: "custom",
                    beforeSvgIcon: undefined,
                    afterSvgIcon: undefined,
                    transition: "1",
                    previewHover: "0",
                    radius: "8px",
                    hoverRadius: "",
                    color: "rgb(0, 0, 0)",
                    hoverColor: "",
                    background: "",
                    hoverBackground: "",
                    borderColor: "rgba(0, 0, 0, 0)",
                    hoverBorderColor: "#000000",
                    borderWidth: "2px",
                    hoverBorderWidth: "2px",
                    borderStyle: "solid",
                    hoverBorderStyle: "solid",
                    shadow: "0px 10px 20px 0 rgba(0, 0, 0, 0.1)",
                    hoverShadow: "0 4px 4px 0 rgba(0, 0, 0, 0)",
                    link: "",
                    linkTarget: "_blank",
                    linkType: "link",
                    linkDetail: "",
                },
            },

            {
                id: "normal-7",
                attrs: {
                    text: "BUTTON",
                    animation: "",
                    padding: "8px 30px",
                    theme: "custom",
                    beforeSvgIcon: undefined,
                    afterSvgIcon: undefined,
                    transition: "1",
                    previewHover: "0",
                    radius: "",
                    hoverRadius: "",
                    color: "rgb(223, 17, 109)",
                    hoverColor: "rgb(255, 255, 255)",
                    background: "",
                    hoverBackground: "rgb(223, 17, 109)",
                    borderColor: "rgb(223, 17, 109)",
                    hoverBorderColor: "rgb(223, 17, 109)",
                    borderWidth: "2px",
                    hoverBorderWidth: "2px",
                    borderStyle: "solid",
                    hoverBorderStyle: "solid",
                    shadow: "",
                    hoverShadow: "",
                    link: "",
                    linkTarget: "_blank",
                    linkType: "link",
                    linkDetail: "",
                },
            },
            {
                id: "normal-8",
                attrs: {
                    text: "BUTTON",
                    animation: "",
                    padding: "8px 30px",
                    theme: "custom",
                    beforeSvgIcon: undefined,
                    afterSvgIcon: {
                        name: "",
                        source: "https://static.jsmo.xin/uebuilder/public-resource/lottie-icon/system-regular-32-videocam.lottie",
                    },
                    transition: "1",
                    previewHover: "0",
                    radius: "",
                    hoverRadius: "",
                    color: "rgb(255, 255, 255)",
                    hoverColor: "rgb(0, 0, 0)",
                    background: "rgb(0, 0, 0)",
                    hoverBackground: "rgba(255, 255, 255, 0)",
                    borderColor: "#000000",
                    hoverBorderColor: "#000000",
                    borderWidth: "2px",
                    hoverBorderWidth: "2px",
                    borderStyle: "solid",
                    hoverBorderStyle: "solid",
                    shadow: "",
                    hoverShadow: "",
                    link: "",
                    linkTarget: "_blank",
                    linkType: "link",
                    linkDetail: "",
                },
            },
            {
                id: "normal-9",
                attrs: {
                    text: "BUTTON",
                    animation: "",
                    padding: "8px 0px",
                    theme: "custom",
                    beforeSvgIcon: undefined,
                    afterSvgIcon: {
                        name: "",
                        source: "https://static.jsmo.xin/uebuilder/public-resource/lottie-icon/system-regular-161-trending-flat.lottie",
                    },
                    transition: "1",
                    previewHover: "0",
                    radius: "",
                    hoverRadius: "",
                    color: "rgb(0, 0, 0)",
                    hoverColor: "rgb(17, 99, 223)",
                    background: "",
                    hoverBackground: "",
                    borderColor: "#000000",
                    hoverBorderColor: "rgb(17, 99, 223)",
                    borderWidth: "0px 0px 1px 0px",
                    hoverBorderWidth: "0px 0px 1px 0px",
                    borderStyle: "solid",
                    hoverBorderStyle: "solid",
                    shadow: "",
                    hoverShadow: "",
                    link: "",
                    linkTarget: "_blank",
                    linkType: "link",
                    linkDetail: "",
                },
            },
            {
                id: "normal-10",
                attrs: {
                    text: "BUTTON",
                    animation: "",
                    padding: "8px 20px",
                    theme: "custom",
                    beforeSvgIcon: undefined,
                    afterSvgIcon: {
                        name: "",
                        source: "https://static.jsmo.xin/uebuilder/public-resource/lottie-icon/system-regular-41-home.lottie",
                    },
                    transition: "1",
                    previewHover: "0",
                    radius: "",
                    hoverRadius: "",
                    color: "rgb(0, 0, 0)",
                    hoverColor: "",
                    background: "",
                    hoverBackground: "",
                    borderColor: "#000000",
                    hoverBorderColor: "",
                    borderWidth: "2px",
                    hoverBorderWidth: "",
                    borderStyle: "solid",
                    hoverBorderStyle: "",
                    shadow: "8px 8px 0px 0 rgb(0, 0, 0)",
                    hoverShadow: "0 4px 4px 0 rgba(0, 0, 0, 0)",
                    link: "",
                    linkTarget: "_blank",
                    linkType: "link",
                    linkDetail: "",
                },
            },
            {
                id: "normal-11",
                attrs: {
                    text: "BUTTON",
                    animation: "",
                    padding: "8px 20px",
                    theme: "custom",
                    beforeSvgIcon: undefined,
                    afterSvgIcon: {
                        name: "",
                        source: "https://static.jsmo.xin/uebuilder/public-resource/lottie-icon/system-regular-75-attachment.lottie",
                    },
                    transition: "1",
                    previewHover: "0",
                    radius: "8px",
                    hoverRadius: "",
                    color: "rgb(255, 255, 255)",
                    hoverColor: "",
                    background: "rgb(59, 130, 246)",
                    hoverBackground: "",
                    borderColor: "",
                    hoverBorderColor: "",
                    borderWidth: "",
                    hoverBorderWidth: "",
                    borderStyle: "",
                    hoverBorderStyle: "",
                    shadow: "0px 8px 0px 0 rgb(37, 99, 235)",
                    hoverShadow: "0 6px 0px 0 rgb(37, 99, 235)",
                    link: "",
                    linkTarget: "_blank",
                    linkType: "link",
                    linkDetail: "",
                },
            },

            {
                id: "normal-1",
                attrs: {
                    text: "BUTTON",
                    animation: "",
                    padding: "8px 30px",
                    theme: "custom",
                    beforeSvgIcon: undefined,
                    afterSvgIcon: {
                        name: "",
                        source: "https://static.jsmo.xin/uebuilder/public-resource/lottie-icon/system-regular-69-document-scan.lottie",
                    },
                    transition: "1",
                    previewHover: "0",
                    radius: "100px",
                    hoverRadius: "",
                    color: "#ffffff",
                    hoverColor: "",
                    background: "linear-gradient(135deg, rgb(9, 149, 67) 0%, rgb(248, 237, 34) 100%)",
                    hoverBackground: "",
                    borderColor: "",
                    hoverBorderColor: "",
                    borderWidth: "",
                    hoverBorderWidth: "",
                    borderStyle: "",
                    hoverBorderStyle: "",
                    shadow: "",
                    hoverShadow: "0 4px 4px 0 rgba(68, 153, 37, 0.3)",
                    link: "",
                    linkTarget: "_target",
                    linkType: "link",
                    linkDetail: "",
                },
            },
            {
                id: "normal-3",
                attrs: {
                    text: "BUTTON",
                    animation: "",
                    padding: "8px 30px",
                    theme: "custom",
                    beforeSvgIcon: undefined,
                    afterSvgIcon: {
                        name: "",
                        source: "https://static.jsmo.xin/uebuilder/public-resource/lottie-icon/system-regular-161-trending-flat.lottie",
                    },
                    transition: "1",
                    previewHover: "0",
                    radius: "100px",
                    hoverRadius: "",
                    color: "#ffffff",
                    hoverColor: "",
                    background: "linear-gradient(135deg, rgb(245, 203, 96) 0%, rgb(228, 57, 5) 100%)",
                    hoverBackground: "linear-gradient(135deg, rgb(255, 166, 46) 0%, #ea4d2c 100%)",
                    borderColor: "",
                    hoverBorderColor: "",
                    borderWidth: "",
                    hoverBorderWidth: "",
                    borderStyle: "",
                    hoverBorderStyle: "",
                    shadow: "",
                    hoverShadow: "0 5px 10px 0 rgba(255, 96, 0, 0.3)",
                    link: "",
                    linkTarget: "_target",
                    linkType: "link",
                    linkDetail: "",
                },
            },
        ],
    },
    outline: {
        name: "线框",
        options: [
            {
                id: "outline-1",
                attrs: {
                    text: "BUTTON",
                    animation: "",
                    padding: "8px 30px",
                    theme: "outline",
                    beforeSvgIcon: undefined,
                    afterSvgIcon: undefined,
                    transition: "1",
                    previewHover: "0",
                    radius: "100px",
                    hoverRadius: "",
                    color: "rgb(17, 99, 223)",
                    background: "rgb(255, 255, 255)",
                    hoverColor: "rgb(17, 99, 223)",
                    hoverBackground: "rgb(255, 255, 255)",
                    borderColor: "",
                    hoverBorderColor: "",
                    borderWidth: "",
                    hoverBorderWidth: "",
                    borderStyle: "",
                    hoverBorderStyle: "",
                    shadow: "0 4px 4px 0 rgba(17, 99, 223, 25%)",
                    hoverShadow: "",
                    link: "",
                    linkTarget: "",
                    linkType: "link",
                    linkDetail: "",
                },
            },
            {
                id: "outline-2",
                attrs: {
                    text: "BUTTON",
                    animation: "",
                    padding: "12px 20px",
                    theme: "outline-circle_icon",
                    beforeSvgIcon: undefined,
                    afterSvgIcon: {
                        source: "https://static.jsmo.xin/uebuilder/public-resource/lottie-icon/system-regular-161-trending-flat.lottie",
                        name: "system-regular-161-trending-flat",
                    },
                    transition: "1",
                    previewHover: "0",
                    radius: "100px",
                    hoverRadius: "",
                    color: "rgb(17, 99, 223)",
                    background: "rgb(255, 255, 255)",
                    hoverColor: "rgb(17, 99, 223)",
                    hoverBackground: "rgb(255, 255, 255)",
                    borderColor: "",
                    hoverBorderColor: "",
                    borderWidth: "",
                    hoverBorderWidth: "",
                    borderStyle: "",
                    hoverBorderStyle: "",
                    shadow: "0 4px 4px 0 rgba(17, 99, 223, 25%)",
                    hoverShadow: "",
                    link: "",
                    linkTarget: "",
                    linkType: "link",
                    linkDetail: "",
                },
            },
            {
                id: "outline-3",
                attrs: {
                    text: "BUTTON",
                    animation: "",
                    padding: "12px 20px",
                    theme: "outline-circle_icon",
                    beforeSvgIcon: {
                        source: "https://static.jsmo.xin/uebuilder/public-resource/lottie-icon/system-regular-41-home.lottie",
                        name: "lottieIcon",
                    },
                    afterSvgIcon: undefined,
                    transition: "1",
                    previewHover: "0",
                    radius: "100px",
                    hoverRadius: "",
                    color: "rgb(17, 99, 223)",
                    background: "rgb(255, 255, 255)",
                    hoverColor: "rgb(17, 99, 223)",
                    hoverBackground: "rgb(255, 255, 255)",
                    borderColor: "",
                    hoverBorderColor: "",
                    borderWidth: "",
                    hoverBorderWidth: "",
                    borderStyle: "",
                    hoverBorderStyle: "",
                    shadow: "0 4px 4px 0 rgba(17, 99, 223, 25%)",
                    hoverShadow: "",
                    link: "",
                    linkTarget: "",
                    linkType: "link",
                    linkDetail: "",
                },
            },
        ],
    },
    rotate: {
        name: "3D 翻转",
        options: [
            {
                id: "rotate-1",
                attrs: {
                    text: "BUTTON",
                    animation: "",
                    padding: "8px 30px",
                    theme: "rotate",
                    beforeSvgIcon: undefined,
                    afterSvgIcon: undefined,
                    transition: "1",
                    previewHover: "0",
                    radius: "",
                    hoverRadius: "",
                    color: "rgb(17, 99, 223)",
                    background: "rgb(255, 255, 255)",
                    hoverColor: "",
                    hoverBackground: "",
                    borderColor: "",
                    hoverBorderColor: "",
                    borderWidth: "",
                    hoverBorderWidth: "",
                    borderStyle: "",
                    hoverBorderStyle: "",
                    shadow: "",
                    hoverShadow: "",
                    link: "",
                    linkTarget: "",
                    linkType: "link",
                    linkDetail: "",
                },
            },
            {
                id: "rotate-2",
                attrs: {
                    text: "BUTTON",
                    animation: "",
                    padding: "8px 30px",
                    theme: "rotate-icon",
                    beforeSvgIcon: {
                        source: "https://static.jsmo.xin/uebuilder/public-resource/lottie-icon/system-regular-161-trending-flat.lottie",
                        name: "system-regular-161-trending-flat",
                    },
                    afterSvgIcon: undefined,
                    transition: "1",
                    previewHover: "0",
                    radius: "",
                    hoverRadius: "",
                    color: "rgb(17, 99, 223)",
                    hoverColor: "",
                    background: "rgb(255, 255, 255)",
                    hoverBackground: "",
                    borderColor: "",
                    hoverBorderColor: "",
                    borderWidth: "",
                    hoverBorderWidth: "",
                    borderStyle: "",
                    hoverBorderStyle: "",
                    shadow: "",
                    hoverShadow: "",
                    link: "",
                    linkTarget: "",
                    linkType: "link",
                    linkDetail: "",
                },
            },
            {
                id: "rotate-3",
                attrs: {
                    text: "BUTTON",
                    animation: "",
                    padding: "8px 30px",
                    theme: "rotate-icon_reverse",
                    beforeSvgIcon: {
                        source: "https://static.jsmo.xin/uebuilder/public-resource/lottie-icon/system-regular-161-trending-flat.lottie",
                        name: "system-regular-161-trending-flat",
                    },
                    afterSvgIcon: undefined,
                    transition: "1",
                    previewHover: "0",
                    radius: "",
                    hoverRadius: "",
                    color: "rgb(17, 99, 223)",
                    hoverColor: "",
                    background: "rgb(255, 255, 255)",
                    hoverBackground: "",
                    borderColor: "",
                    hoverBorderColor: "",
                    borderWidth: "",
                    hoverBorderWidth: "",
                    borderStyle: "",
                    hoverBorderStyle: "",
                    shadow: "",
                    hoverShadow: "",
                    link: "",
                    linkTarget: "",
                    linkType: "link",
                    linkDetail: "",
                },
            },
        ],
    },
    wave: {
        name: "波浪动效",
        options: [
            {
                id: "wave-1",
                attrs: {
                    text: "BUTTON",
                    animation: "",
                    padding: "8px 30px",
                    theme: "wave",
                    beforeSvgIcon: undefined,
                    afterSvgIcon: undefined,
                    transition: "1",
                    previewHover: "0",
                    radius: "100px",
                    hoverRadius: "",
                    color: "#ffffff",
                    hoverColor: "",
                    background: "#7955f4",
                    hoverBackground: "",
                    borderColor: "",
                    hoverBorderColor: "",
                    borderWidth: "",
                    hoverBorderWidth: "",
                    borderStyle: "",
                    hoverBorderStyle: "",
                    shadow: "0 4px 4px 0 rgba(124, 87, 244, 25%)",
                    hoverShadow: "",
                    link: "",
                    linkTarget: "",
                    linkType: "link",
                    linkDetail: "",
                },
            },
            {
                id: "wave-2",
                attrs: {
                    text: "BUTTON",
                    animation: "",
                    padding: "12px 20px",
                    theme: "wave-circle_icon",
                    beforeSvgIcon: undefined,
                    afterSvgIcon: {
                        source: "https://static.jsmo.xin/uebuilder/public-resource/lottie-icon/system-regular-161-trending-flat.lottie",
                        name: "system-regular-161-trending-flat",
                    },
                    transition: "1",
                    previewHover: "0",
                    radius: "100px",
                    hoverRadius: "",
                    color: "#ffffff",
                    hoverColor: "",
                    background: "#7955f4",
                    hoverBackground: "",
                    borderColor: "",
                    hoverBorderColor: "",
                    borderWidth: "",
                    hoverBorderWidth: "",
                    borderStyle: "",
                    hoverBorderStyle: "",
                    shadow: "0 4px 4px 0 rgba(124, 87, 244, 25%)",
                    hoverShadow: "",
                    link: "",
                    linkTarget: "",
                    linkType: "link",
                    linkDetail: "",
                },
            },
            {
                id: "wave-3",
                attrs: {
                    text: "BUTTON",
                    animation: "",
                    padding: "12px 20px",
                    theme: "wave-circle_icon",
                    beforeSvgIcon: {
                        source: "https://static.jsmo.xin/uebuilder/public-resource/lottie-icon/system-regular-41-home.lottie",
                        name: "lottieIcon",
                    },
                    afterSvgIcon: undefined,
                    transition: "1",
                    previewHover: "0",
                    radius: "100px",
                    hoverRadius: "",
                    color: "#ffffff",
                    hoverColor: "",
                    background: "#7955f4",
                    hoverBackground: "",
                    borderColor: "",
                    hoverBorderColor: "",
                    borderWidth: "",
                    hoverBorderWidth: "",
                    borderStyle: "",
                    hoverBorderStyle: "",
                    shadow: "0 4px 4px 0 rgba(124, 87, 244, 25%)",
                    hoverShadow: "",
                    link: "",
                    linkTarget: "",
                    linkType: "link",
                    linkDetail: "",
                },
            },
        ],
    },
};

export default btnLib;
